### ISSUE TITLE
2020 data?

### ISSUE THREAD

**Issue by mnowatzke** [ornldaac/daymet-single-pixel-batch#2]
When will the 2020 data be available for the single pixel API? Thanks!

**Comment by michele-ornl** [comment]
Hi @mnowatzke
Yes, Daymet V4 2020 data will be available through the single pixel API and all other access methods.  
Expect to see that late this week or early next.
Thanks for reaching out.

**Comment by mnowatzke** [comment]
Thank you, @michele-ornl !
